services:
  api:
    container_name: backend-test
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    depends_on:
      mysql-test:
        condition: service_healthy
    ports:
      - 50010:5000
    volumes:
      - .:/app
  mysql-test:
    platform: linux/amd64
    build: ./.docker-compose/mysql
    container_name: mysql-test
    env_file:
      - .env
    volumes:
      - .docker-compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - test-mysql-data:/var/lib/mysql
      - test-mysql-log:/var/log/mysql
      - .docker-compose/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 53306:3306
  pma-test:
    image: amd64/phpmyadmin:latest
    container_name: pma-test
    ports:
      - 63306:80
    environment:
      PMA_HOST: mysql-test
    volumes:
      - .docker-compose/pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    depends_on:
      - mysql-test
volumes:
  test-mysql-data:
  test-mysql-log: